### ISSUE TITLE
"Benchmarks" web page is blank

### ISSUE THREAD

**Issue by Kurren123** [easafe/purescript-flame#13]
The [benchmarks ](https://flamepurs.org/benchmarks) web page is showing as blank for me: 

![image](https://user-images.githubusercontent.com/3525980/79908062-82fb3380-8412-11ea-83bc-3cd2c1bec6b1.png)

**Comment by easafe** [comment]
Hello @Kurren123 , it is because I haven't got to it yet 😅 -- it is on my roadmap, alongside with looking for alternatives to snabdom

(P.S.: you probably mean deprecated [here](https://github.com/Kurren123/k-dropdown-container))

**Comment by s0kil** [comment]
@Kurren123  I'm towards another alternative to snabdom, it is too heavy.
Have you heard about https://github.com/ryansolid/solid?

**Comment by Kurren123** [comment]
@easafe thanks 🙂
Why are you looking for an alternative to snabdom? (I don’t know much about it so just out of interest)

**Comment by easafe** [comment]
I am not the biggest fan of its API, and I suspect there are some more performant options out there (like the one linked by @s0kil ). Unfortunately, I won't be looking into it as soon as I would like.

**Comment by Kurren123** [comment]
One more question: Is it reasonable to say that this is more or less as fast as headwig? Also does it offer hedwig's [animation features](https://github.com/utkarshkukreti/purescript-hedwig#animations)?

Thanks

**Comment by easafe** [comment]
>  Is it reasonable to say that this is more or less as fast as headwig? 

It doesn't make use of snabdom thunks, and the core is in Purescript, but it should be in the same ballpark. Hard to say how well it stacks in the grand scheme of things without benchmarking tho.

> Also does it offer hedwig's animation features?

No, but I find it curious that it offered animations but no way to do custom events :)

**Comment by easafe** [comment]
The page is no longer blank, also benchmark code has been added. Later on I will send a PR to include it on the official results.
