### ISSUE TITLE
How to use with spago?

### ISSUE THREAD

**Issue by eikek** [easafe/purescript-flame#15]
Hello, 
I'm coming from elm and scala and I'm just trying out purescript and found this library. I'm quite lost with all the build tools used in purescript. So I'm sorry if this sounds completely stupid: The tutorials I went through made me use spago. Now this lib mentions bower. Can I install this lib via spago somehow? Or can I use both togehter?
Thank you!

**Comment by easafe** [comment]
Hello @eikek !

I am not super familiar with spago, but I think you could manually add the library to the set like shown in the readme https://github.com/purescript/spago/blob/master/README.md#add-a-package-to-the-package-set

I will take a look into whats needed to add the library to the upstream package set later :)

**Comment by eikek** [comment]
Hello @easafe ,
thank you very much for the fast reply. Oh and I apologize for not looking at this README very thoroughly. I seem to have overlooked that section…:/. I just also found that the big comment section in the generated `packages.dhall` contains useful info. I can now continue experimenting :)  Sorry for the noise!

**Comment by easafe** [comment]
Glad to help!

**Comment by whitecolor** [comment]
@easafe it still seems not to be possible to install with `spago install purescript-flame`, though the project it self uses spago.

**Comment by easafe** [comment]
Hi @whitecolor , yea, it is still not in the package set. I think you should specify a tag for the `version` tho -- stuff on master might not be quite ready for release yet.
