### ISSUE TITLE
Feature proposal: vnode hooks

### ISSUE THREAD

**Issue by chekoopa** [easafe/purescript-flame#17]
Snabbdom has a really powerful feature to inject functions into VNodes (https://github.com/snabbdom/snabbdom#hooks), and we use hooks in Hedwig (I even had to [fork it](https://github.com/chekoopa/purescript-hedwig/tree/vnode-hooks) to add them) for some tricks, such as Markdown rendering.

We consider switching to Flame (as Hedwig seems to be discontinued), but for now, it misses some low-level features, such as hooks, keyed, and thunks (however, we don't use it, but laziness is a great perk).

`hooks` attribute is situated in [VNodeData](https://github.com/easafe/purescript-flame/blob/ee3c6243e90d2b8e25a90fb5cac27f87263bdc69/src/Flame/Types.purs#L19), so it seems to enable hooks being treated as a NodeData, like `NodeHook string (VNode -> Effect message)` (but it actually needs an additional for update hooks with two VNode parameters), and therefore being used as a node attribute (like, ToNodeHook1 and ToNodeHook2, or something more static).

**Comment by easafe** [comment]
Hello @chekoopa , thank you for your suggestion. 

Some use cases can be accomplished by (carefully) using the `innerHtml` attribute (e.g., markdown rendering) or using signals. That being said, keys, thunks and hooks would indeed be a great addition.

Perhaps you could adapt the work for hooks in your fork to flame? PRs are always welcome :)

As for keys and thunks, I think neither is very complex to implement (`key` for example is just a snabbdom attribute). Maybe this could fit in the following release, tho I still need time to research.

**Comment by chekoopa** [comment]
Both `innerHtml` and signals (and even effects with `getElementById`, we used to have that) are dirty hacks, IMHO.

The problem is Hedwig having a different 'vnode baking' architecture, so I can't adapt it straightforward. However, I've researched your code for a bit and have some picture in mind about hooks implementation, would try carve some time and make a fork. 

BTW, `key` is also [can be added](https://github.com/snabbdom/snabbdom#key--string--number) as NodeData. It may be a little unusual to have a vnode key as an attribute, but Hedwig has [the same UX](https://github.com/chekoopa/purescript-hedwig/blob/vnode-hooks/src/Hedwig/Foreign.purs).

**Comment by easafe** [comment]
> Both innerHtml and signals (and even effects with getElementById, we used to have that) are dirty hacks, IMHO.

> More often than not, hah.
The problem is Hedwig having a different 'vnode baking' architecture, so I can't adapt it straightforward. However, I've researched your code for a bit and have some picture in mind about hooks implementation, would try carve some time and make a fork.

Sure!

> BTW, key is also can be added as NodeData. It may be a little unusual to have a vnode key as an attribute, but Hedwig has the same UX.

That makes it easier to use/modify functions that construct nodes.

**Comment by chekoopa** [comment]
I wonder if hooks should have the message return type, like events.

**Comment by chekoopa** [comment]
Actually, safe-ish VNode mutation could be reached with map-like hook function, which returns new VNode object, and the under-the-hood wrapper performs data replacement (I don't know what would happen if we replace the whole node).

And all hook functions are `Effect Unit`, if we're talking in Purs conventions.
So, if we would make wrapped Purs-compatible hook functions, they would look like this:

Name | Classic arguments | Possible Purs signature
-- | -- | --
init | vnode | VNode -> Effect VNode
create | emptyVnode, vnode | VNode -> VNode -> Effect VNode
insert | vnode | VNode -> Effect VNode
prepatch | oldVnode, vnode | VNode -> VNode -> Effect VNode
update | oldVnode, vnode | VNode -> VNode -> Effect VNode
postpatch | oldVnode, vnode | VNode -> VNode -> Effect VNode
destroy | vnode | VNode -> Effect Unit
remove | vnode, removeCallback | VNode -> Effect Unit -> Effect Unit ¹

¹ Don't know whether this hook should be implemented.

But, there's a big problem about vnodes. Snabbdom doesn't restrict adding custom properties to VNodes, and we are using that in our Markdown implementation. Elm Markdown library uses local model data (https://github.com/evancz/elm-markdown/blob/3.0.2/src/Native/Markdown.js), which stays with the node and is used for diffing. We add two fields as for a local node model. With Purs-based implementation it wouldn't be possible. If only we added another field, like `model :: Object Type`, which would be empty for default nodes, but

**Comment by easafe** [comment]
Would all of that be easier if we changed the wrapper functions e.g. [Renderer.purs](/easafe/purescript-flame/blob/master/src/Flame/Renderer/Renderer.purs#L85) to foreign calls? Similar to what hedwig did. Maybe as more features are added, changing (a bit of) type safety for easiness and performance is an acceptable trade off.

I am not sure I follow the need for the local vnode `model` field. Aren't all vnode manipulations done in unsafe js?

**Comment by chekoopa** [comment]
It depends on what you have in mind for Flame. I'm not sure what functions could be converted to foreign (still not fully examined all the renderer internals), but the current state of code is pretty sturdy. The performance point is about benchmarking, I think.

By design, these manipulations are unsafe. The thing I've described above is kind of concept for Purs-compliant low-level FRP vnode hooking. Hooks themselves are rather advanced feature which used mostly by library developers (in Elm it was possible before the 0.19 release). 
So, unsafe hooks are fair for now.

Aside of hooks, keys, and thunks Snabbdom offers module feature. But something tells me that would be too bloated.

**Comment by chekoopa** [comment]
A question about naming conventions. What should we use for hooks' name?
- own naming, like `atInsert`. I've used that in Hedwig, it makes hooks distinctive from other attrs.
- event-like naming, like `onInsert`. It doesn't interfere with events.
- plain hook's name, like `insert`.

I'm now sticking with the first variant, but can change it at any moment before PR.

**Comment by easafe** [comment]
Yeah I plan on adding benchmarks next. The types for hooks, and the first naming convention, sound fine. I will try it out on own my markdown generation too.
