### ISSUE TITLE
Package set publication

### ISSUE THREAD

**Issue by chekoopa** [easafe/purescript-flame#31]
As Flame becomes mature, it should be published ~~at least in the [registry](https://github.com/purescript/registry) and, ideally,~~ in [package sets](https://github.com/purescript/package-sets).

The only concern is unstable API, but right now the framework is pretty usable to be declared about.

UPD: I've double-checked, Flame is already in registry as Bower-published. Still, the point about package sets is up.

**Comment by easafe** [comment]
I think we are set to look into this.

**Comment by chekoopa** [comment]
Okay, so the situation is:
 - Flame is included in the registry already (as in `bower-packages.json`)
 - Pursuit docs [are published](https://pursuit.purescript.org/packages/purescript-flame/1.1.0)

The only step is left is to add the package to [package sets](https://github.com/purescript/package-sets/). 

I think I'll do the PR in 10-15 minutes.

**Comment by chekoopa** [comment]
The PR is up.

https://github.com/purescript/package-sets/pull/968

**Comment by easafe** [comment]
Fantastic! Thanks @chekoopa

**Comment by easafe** [comment]
Alright, it has been merged. Should take a while still to be on the new set, but I will update the docs later.
