### ISSUE TITLE
Runtime error when input element uses the `list` attribute

### ISSUE THREAD

**Issue by liamgoat** [easafe/purescript-flame#39]
I was attempting to build a `view` function that included an `<input>`. That `<input>` made use of a `<datalist>` so it would autocomplete. Here's a cut down example of what I was trying to do:

```PureScript
view :: Model -> Html Message
view model =
  HE.main "main"
    $ [ HE.label [ HA.for "broken-input" ] "Broken input"
      , HE.input [ HA.type' "search", HA.name "broken-input", HA.id "broken-input", HA.list "search-results", HA.value model.searchResult, HA.onInput SearchStuff ]
      , HE.datalist [ HA.id "search-results" ] [ HE.option_ "Search..." ]
      ]
```
On Chrome this generates a runtime error: `Uncaught TypeError: Cannot set property list of #<HTMLInputElement> which has only a getter`
On Firefox this generates the same error (with a different message): `Uncaught TypeError: setting getter-only property "list"`

Seems the problem is Flame creates the Input and attempts to set the `list` attribute after, but since it's read-only this cannot work.

**Comment by easafe** [comment]
Thanks for the bug report, @liamgoat . 

Looks like `list` is being created as a property instead of attribute. This should be an easy fix, but I am afraid I will only be able to include it on the next (likely breaking) release. As a workaround, you could use `HA.createAttribute "list"` instead of `HA.list`. Does that work for you?

**Comment by GiantGoatIT** [comment]
@easafe Thanks, yes that sounds like a perfectly acceptable workaround. No worries on when the fix will be available, I'm not exactly paying a support contract here :)
