### ISSUE TITLE
Fix documentation website

### ISSUE THREAD

**Issue by easafe** [easafe/purescript-flame#43]
I can't afford to renew `flamepurs.org` which has now expired. Github does not accept projects to use _username_.github.io/_project_ if a custom domain is enabled for the user, so the likely best solution is just to create an organization.

**Comment by JivanRoquet** [comment]
Hello, since this issue il has been closed, am I correct to assume that the documentation website is available again? Mind if I ask where can it be found?

**Comment by easafe** [comment]
Hi @JivanRoquet ,  I placed it on https://flame.asafe.dev. I realized that making a new org would be more friction than just changing the domain (which can also be redirected to the old domain, if I can later on renew it).

**Comment by JivanRoquet** [comment]
Thanks for the quick reply @easafe!

Haskeller here, completely noob to PS and after looking at some alternatives (cough cough Halogen cough cough), Flame looks like the most promising option as it combines Elm's simplicity and straightforwardness with PS advanced type system, without trying to overuse it.

Quick Q, the documentation only mentions `bower`. Would there be some example of installation using `spago` instead? I can tell from past issues that Flame migrated to Spago but it doesn't seem to be reflected in the docs yet (again, pure PS noob here so all this is very foreign to me, I'm just looking for a way to start experimenting/learning quickly on Flame).

Many thanks, again.

**Comment by easafe** [comment]
No problem @JivanRoquet , glad to help.

Flame isn't on the registry yet (it has reached 1.0 very recently) so you can't install it directly with spago. You can however add it manually as a dependency to your `packages.dhall` like on here https://github.com/easafe/purescript-flame/issues/15 or https://github.com/melanchat/melanchat/blob/master/packages.dhall#L195 (might want to use tag versions instead of commit hashs tho)
