### ISSUE TITLE
Monoid instance for Html a

### ISSUE THREAD

**Issue by iclanzan** [easafe/purescript-flame#53]
Is it possible to give `Html a` a Monoid instance like React.Basic is doing for `JSX`?

**Comment by easafe** [comment]
Hello @iclanzan , I am afraid I don't know what React.Basic uses monoids for. Is it a list like instance?

**Comment by iclanzan** [comment]
https://pursuit.purescript.org/packages/purescript-react-basic/16.0.0/docs/React.Basic#t:JSX

> `JSX` is a `Monoid`:
>
> - `append`
> Merge two `JSX` nodes using `React.Fragment`.
> - `mempty`
> The empty node; renders nothing.
>
> **Hint: Many useful utility functions already exist for Monoids. For example, `guard` can be used to conditionally render a subtree of components.**

**Comment by easafe** [comment]
I suppose this could be done. Though flame doesn't really have an equivalent to ```empty``` right now.

**Comment by iclanzan** [comment]
I wonder if `mempty = fragment []` would work.
