### ISSUE TITLE
impossible to execute the ssr example

### ISSUE THREAD

**Issue by tcastelly** [easafe/purescript-flame#69]
Hello,

I'm trying the ServerSide Rendering example but I have multiple problems. [I tried to fix them](https://github.com/tcastelly/purescript-flame/commit/b33ece35b39cdee02daf062428921bee5063b817), now I can build but I still have an error:

```
npm run server-side-rendering

> server-side-rendering
> npm run example-server-side-rendering && node examples/ServerSideRendering/dist/server-side-rendering-server.js


> example-server-side-rendering
> npm run example-server-side-rendering-server && npm run example-server-side-rendering-client


> example-server-side-rendering-server
> parcel build examples/ServerSideRendering/Server/server-side-rendering-server.js --dist-dir examples/ServerSideRendering/dist

✨ Built in 148ms

examples/ServerSideRendering/dist/server-side-rendering-server.js    178.73 KB    2.01s

> example-server-side-rendering-client
> parcel build examples/ServerSideRendering/Client/server-side-rendering-client.js --dist-dir examples/ServerSideRendering/dist

✨ Built in 115ms

examples/ServerSideRendering/dist/server-side-rendering-client.js    43.69 KB    1.41s
/Users/tcy/Documents/dev/workspaces/purescript/purescript-flame/examples/ServerSideRendering/dist/server-side-rendering-server.js:2
[...]
{return jc(i)(e)}))}(),Uc=function(e){return Mc(e.path)([Pc])?Ic:Lc};pc(3e3)(Uc)(Go("Server running on http://localhost:3000"))()})();


TypeError: n(...).createServer is not a function
    at /Users/tcy/Documents/dev/workspaces/purescript/purescript-flame/examples/ServerSideRendering/dist/server-side-rendering-server.js:2:159278
    at /Users/tcy/Documents/dev/workspaces/purescript/purescript-flame/examples/ServerSideRendering/dist/server-side-rendering-server.js:2:159320
    at /Users/tcy/Documents/dev/workspaces/purescript/purescript-flame/examples/ServerSideRendering/dist/server-side-rendering-server.js:2:161358
    at Object.<anonymous> (/Users/tcy/Documents/dev/workspaces/purescript/purescript-flame/examples/ServerSideRendering/dist/server-side-rendering-server.js:2:161362)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

Few informations:
```
spago --version
0.20.9

node --version
v16.14.2
```

Thanks a lot for this project, I'm looking forward to be able to play with the SSR :)

**Comment by easafe** [comment]
Hi @tcastelly , thanks for catching this, looks like I didn't update the examples for the newer compiler version. 

Porting the your fixes, I think it is something to do with how parcel is bundling the code. `createServer` comes from `HTTPure`, and the server side part works if called directly from the output folder.

I will try to take a look at it, but in the meanwhile there shouldn't be any issues with the library code, if you want to try it yourself.

**Comment by tcastelly** [comment]
Because now NodeJS works with ESM module, I guess it's possible to don't try to build the server part with Parcel.

It should works by calling directly `examples/ServerSideRendering/Server/server-side-rendering-server.js`.  I guess I missed something because click on the "Roll" button do nothing.

[here a small fix](https://github.com/tcastelly/purescript-flame/commit/978337e0b1080285b4fb1879f9d2b3500f02b730) to import ESM.

**Comment by easafe** [comment]
Okay, that was a bit of work, but all the examples should be working now.

**Comment by tcastelly** [comment]
It works! Thank you so much for your help!

**Comment by tcastelly** [comment]
I'm not sure if it's a problem or not, but now the client part build is heavier. About 1,44mB. Is it something normal?

```
du -sh examples/ServerSideRendering/dist/*
1.4M	examples/ServerSideRendering/dist/server-side-rendering-client.js
2.3M	examples/ServerSideRendering/dist/server-side-rendering-client.js.map
```

**Comment by easafe** [comment]
Yeah, debugging artifact, just removed it. But PureScript bundles are on the heavier side, code splitting + compression is a must.
