### ISSUE TITLE
impossible to build examples

### ISSUE THREAD

**Issue by tcastelly** [easafe/purescript-flame#71]
Hello,

Maybe I did something wrong, but it seams that is not possible anymore to compile examples.

```bash
spago build
npm ci
npm run build-examples
```

There is no `output/Examples.*` so parcel can't build. And I have a lot of errors like this:
```
 Build failed.

@parcel/core: Failed to resolve '../../output/Examples.EffectList.Affjax.Main' from './examples/Affjax/affjax.js'

  /private/tmp/purescript-flame/examples/Affjax/affjax.js:1:22
  > 1 | import { main } from '../../output/Examples.EffectList.Affjax.Main';
  >   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 | main();
```

I updated the `spago.dhall` to add the examples folder to try to fix the problem.

---
purs --version
0.15.6

spago --version
0.20.9

node --version
v18.12.0

**Comment by easafe** [comment]
Hello Thomas,

You should use examples.dhall like `npm run test` does, e.g. `spago -x examples.dhall build`. Does that fix it for you?

**Comment by tcastelly** [comment]
Yes it works. Thank you very much for your help.
