### ISSUE TITLE
The `tabindex` attribute does not work due to capitalization

### ISSUE THREAD

**Issue by hakonrk** [easafe/purescript-flame#73]
The `tabIndex` attribute does not do anything because Flame spells it with a lowercase i.

By "does not do anything" I mean that when I inspect the generated HTML in the browser, the attribute does not appear at all (disregarding capitalization). For some reason, it worked fine after I replaced all occurrences of `tabindex` with `tabIndex` in src/Flame/Html/Attribute.purs and src/Flame/Html/Attribute/Internal.purs.

**Comment by easafe** [comment]
Thanks for spotting it @hakonrk 

It should be fixed now

**Comment by hakonrk** [comment]
I can confirm that the latest master works perfectly now. Thanks for the quick merge, and thanks for all the work you have put into this great library!

**Comment by easafe** [comment]
Thank you!
